language: python
cache: pip

python:
  - "3.7"

env:
  - DJANGO=2.2

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: DJANGO=2.2

    - python: "3.7"
      env: TOXENV=isort
      before_install: skip

    - python: "3.7"
      env: TOXENV=black
      before_install: skip

    # - { python: "3.7", env: TOXENV=docs }

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
